### ISSUE TITLE
Figure out how to focus a comonad

### ISSUE THREAD

**Issue by syaiful6** [syaiful6/purescript-coui#1]
With this implementation https://github.com/syaiful6/purescript-coui/blob/master/src/Coui/Aff/Driver/Eval.purs#L70, limitation of running side effects in @paf31 purescript-comonad-ui solved by using CoT monad transformer directly rather than using pairing.

Now we need to think how to compose components, one can be achieved by taking their Day convolution. But it seems make the type signature grow more complex. so, we may need similir machinery of Lenses. So we can focus them instead.

@paf31 any idea how this can be achieved?

**Comment by paf31** [comment]
One way I had considered is to use the symmetric monoidal structure given by `Day` on comonads, to define something like lenses for accessing parts of a larger comonad. That would only give you a way to talk about independent state though. Shared state could be a little tricker, although I'm not sure.

**Comment by syaiful6** [comment]
@paf31 great idea, i think i will try it and figure out what we need really. this repo as exercies anyway.
